# Generated by Django 3.1.7 on 2021-02-21 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_auto_20210221_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://image.flaticon.com/icons/png/512/34/34754.png', max_length=500),
        ),
    ]
