# Generated by Django 3.1.7 on 2021-02-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_auto_20210221_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://www.flaticon.com/premium-icon/icons/svg/204/204938.svg', max_length=500),
        ),
    ]
